# docker-compose.yml (단일 프로젝트 최종본)
version: '3.8'

services:
  # Nginx 경비실
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app # 'app' 서비스에 의존
    networks:
      - app-network

  # ‼️ Node.js 통합 앱 서비스 (PM2가 내부에서 두 개를 실행)
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  # 4. 데이터베이스 (변경 없음)
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: