# docker-compose.yml (단일 프로젝트 최종본)
version: '3.8'

services:
  # Nginx 경비실
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d

      # ‼️ 여기가 핵심 2: SSL 인증서 폴더를 공유합니다.
      # 서버의 /home/ubuntu/live/ 폴더를, 컨테이너의 /etc/letsencrypt/live/ 폴더로 연결합니다.
      - /home/ubuntu/live:/etc/letsencrypt/live

      # ‼️ 여기가 핵심 3: 사용자 업로드 폴더를 공유합니다.
      # 서버의 /home/ubuntu/memora/uploads 폴더를, 컨테이너의 /home/ubuntu/memora/uploads 폴더로 연결합니다.
      - /home/ubuntu/memora/uploads:/home/ubuntu/memora/uploads
    depends_on:
      - app
    networks:
      - app-network

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # ‼️ Node.js 통합 앱 서비스 (PM2가 내부에서 두 개를 실행)
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  # 4. 데이터베이스 (변경 없음)
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: